# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Genotyping MHC class I and II alleles

repo_url: https://github.com/svm-zhang/polysolver-mod
repo_name: svm-zhang/polysolver-mod
edit_uri: edit/main/docs/

theme:
  name: material
  font: false
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-box
    view: material/eye-circle
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details # make admonition collapsible
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.highlight:
      pygments_lang_class: true
      anchor_linenums: true
      line_spans: __span
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Home: index.md
