context:
  version: "0.1"
  name: polysolver_modern 

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  - path: ./scripts
  - path: ./pyhlatyper

build:
  number: 1
  string: "stable"
  skip:
    - win

requirements:
  host:
    - python >=3.8
  run:
    - python >=3.8
    - numpy
    - pysam
    - polars
    - tqdm
    - samtools >=1.13
    - picard
    - seqkit

test:
  exists:
    bin:
      - samtools
      - seqkit
      - picard
      - hlareforged
      - hlatyper
      - hlafinalizer
      - hlapolysolver
      - polysolver_realigner
      - pyhlatyper

extra:
  maintainers:
    - Simo V. Zhang (svm.zhang@gmail.com)
