context:
  version: "0.2.0"
  name: mhcflow

package:
  name: ${{ name }}
  version: ${{ version }}
  # name: "{{ name }}"
  # version: "{{ version }}"

source:
  - path: ./scripts
  # - path: ./pyhlatyper

build:
  number: 1
  string: "stable"
  skip:
    - win

requirements:
  host:
    - python >=3.10.14
    - pip
  run:
    - samtools
    - picard
    - seqkit
    - python >=3.10.14
    # - numpy
    # - pysam
    # - polars
    # - tqdm

tests:
  - package_contents:
      bin:
        # - samtools
        # - seqkit
        # - picard
        - mhcflow
        - fisher
        - realigner
        - extractor
  # exists:
  #   bin:
  #     - samtools
  #     - seqkit
  #     - picard
  #     - mhcflow
  #     # - polysolvermod
  #     - fisher
  #     - realigner
  #     # - pyhlatyper
  #     - extractor

extra:
  maintainers:
    - Simo V. Zhang (svm.zhang@gmail.com)
